server:
  port: "8080"
  mode: "debug"
  read_timeout: 60
  write_timeout: 60

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "ai_svc_dev"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100

log:
  level: "debug"
  format: "text"
  output: "stdout"
  max_size: 100
  max_backups: 3
  max_age: 7

jwt:
  secret: "dev-jwt-secret-key-change-this-in-production"
  expire_time: 3600
